development:
  adapter: postgresql
  encoding: unicode
  database: myapp
  username: jonathanschack
  password: 
  pool: 5

  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: jonathanschack
  password: 
 
  timeout: 5000