development:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: jonathanschack

  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: jonathanschack
 
  timeout: 5000